[project]
name = "diambra-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "diambra>=0.0.20",
    "diambra-arena>=2.2.7",
    "numpy==1.23.0",
    "pyyaml",
    "yaml",
]
